# Form implementation generated from reading ui file './ui_files/Home.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(392, 441)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(69, 89, 281, 351))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetNoConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ctc_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.ctc_btn.setObjectName("ctc_btn")
        self.verticalLayout.addWidget(self.ctc_btn)
        self.track_model_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.track_model_btn.setObjectName("track_model_btn")
        self.verticalLayout.addWidget(self.track_model_btn)
        self.track_controller_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.track_controller_btn.setObjectName("track_controller_btn")
        self.verticalLayout.addWidget(self.track_controller_btn)
        self.train_model_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.train_model_btn.setObjectName("train_model_btn")
        self.verticalLayout.addWidget(self.train_model_btn)
        self.train_controller_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.train_controller_btn.setObjectName("train_controller_btn")
        self.verticalLayout.addWidget(self.train_controller_btn)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(170, 70, 81, 16))
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.ctc_btn.setText(_translate("Form", "CTC"))
        self.track_model_btn.setText(_translate("Form", "Track Model"))
        self.track_controller_btn.setText(_translate("Form", "Track Controller"))
        self.train_model_btn.setText(_translate("Form", "Train Model"))
        self.train_controller_btn.setText(_translate("Form", "Train Controller"))
        self.label.setText(_translate("Form", "Select Module"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
