# Form implementation generated from reading ui file '.\SoftwareTrainController.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1059, 600)
        MainWindow.setIconSize(QtCore.QSize(24, 44))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1001, 571))
        self.tabWidget.setIconSize(QtCore.QSize(32, 32))
        self.tabWidget.setObjectName("tabWidget")
        self.manual = QtWidgets.QWidget()
        self.manual.setObjectName("manual")
        self.leftdoor = QtWidgets.QCheckBox(parent=self.manual)
        self.leftdoor.setGeometry(QtCore.QRect(340, 280, 131, 41))
        self.leftdoor.setObjectName("leftdoor")
        self.rightdoor = QtWidgets.QCheckBox(parent=self.manual)
        self.rightdoor.setGeometry(QtCore.QRect(340, 270, 111, 21))
        self.rightdoor.setObjectName("rightdoor")
        self.internallight = QtWidgets.QCheckBox(parent=self.manual)
        self.internallight.setGeometry(QtCore.QRect(340, 470, 121, 21))
        self.internallight.setObjectName("internallight")
        self.externallight = QtWidgets.QCheckBox(parent=self.manual)
        self.externallight.setGeometry(QtCore.QRect(340, 490, 121, 21))
        self.externallight.setObjectName("externallight")
        self.textEdit = QtWidgets.QTextEdit(parent=self.manual)
        self.textEdit.setEnabled(False)
        self.textEdit.setGeometry(QtCore.QRect(320, 430, 161, 41))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_3 = QtWidgets.QTextEdit(parent=self.manual)
        self.textEdit_3.setEnabled(False)
        self.textEdit_3.setGeometry(QtCore.QRect(320, 230, 161, 41))
        self.textEdit_3.setObjectName("textEdit_3")
        self.ebrake = QtWidgets.QPushButton(parent=self.manual)
        self.ebrake.setGeometry(QtCore.QRect(750, 10, 231, 101))
        self.ebrake.setObjectName("ebrake")
        self.textEdit_2 = QtWidgets.QTextEdit(parent=self.manual)
        self.textEdit_2.setEnabled(False)
        self.textEdit_2.setGeometry(QtCore.QRect(320, 140, 171, 41))
        self.textEdit_2.setObjectName("textEdit_2")
        self.announcement = QtWidgets.QComboBox(parent=self.manual)
        self.announcement.setGeometry(QtCore.QRect(320, 180, 171, 31))
        self.announcement.setObjectName("announcement")
        self.announcement.addItem("")
        self.announcement.addItem("")
        self.manualtrainfailures = QtWidgets.QTextEdit(parent=self.manual)
        self.manualtrainfailures.setEnabled(False)
        self.manualtrainfailures.setGeometry(QtCore.QRect(320, 320, 161, 41))
        self.manualtrainfailures.setObjectName("manualtrainfailures")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(parent=self.manual)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 291, 521))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.time = QtWidgets.QDateTimeEdit(parent=self.gridLayoutWidget_2)
        self.time.setObjectName("time")
        self.gridLayout_2.addWidget(self.time, 0, 2, 1, 1)
        self.textEdit_8 = QtWidgets.QTextEdit(parent=self.gridLayoutWidget_2)
        self.textEdit_8.setEnabled(False)
        self.textEdit_8.setObjectName("textEdit_8")
        self.gridLayout_2.addWidget(self.textEdit_8, 11, 0, 1, 1)
        self.speedlimit = QtWidgets.QTextEdit(parent=self.gridLayoutWidget_2)
        self.speedlimit.setObjectName("speedlimit")
        self.gridLayout_2.addWidget(self.speedlimit, 1, 2, 1, 1)
        self.temp = QtWidgets.QSpinBox(parent=self.gridLayoutWidget_2)
        self.temp.setWrapping(False)
        self.temp.setFrame(True)
        self.temp.setObjectName("temp")
        self.gridLayout_2.addWidget(self.temp, 11, 2, 1, 1)
        self.authority = QtWidgets.QTextEdit(parent=self.gridLayoutWidget_2)
        self.authority.setObjectName("authority")
        self.gridLayout_2.addWidget(self.authority, 5, 2, 1, 1)
        self.textEdit_15 = QtWidgets.QTextEdit(parent=self.gridLayoutWidget_2)
        self.textEdit_15.setEnabled(False)
        self.textEdit_15.setObjectName("textEdit_15")
        self.gridLayout_2.addWidget(self.textEdit_15, 5, 0, 1, 1)
        self.nextstop = QtWidgets.QTextEdit(parent=self.gridLayoutWidget_2)
        self.nextstop.setObjectName("nextstop")
        self.gridLayout_2.addWidget(self.nextstop, 3, 2, 1, 1)
        self.textEdit_4 = QtWidgets.QTextEdit(parent=self.gridLayoutWidget_2)
        self.textEdit_4.setEnabled(False)
        self.textEdit_4.setObjectName("textEdit_4")
        self.gridLayout_2.addWidget(self.textEdit_4, 1, 0, 1, 1)
        self.amanualnextstop = QtWidgets.QTextEdit(parent=self.gridLayoutWidget_2)
        self.amanualnextstop.setEnabled(False)
        self.amanualnextstop.setObjectName("amanualnextstop")
        self.gridLayout_2.addWidget(self.amanualnextstop, 3, 0, 1, 1)
        self.textEdit_10 = QtWidgets.QTextEdit(parent=self.gridLayoutWidget_2)
        self.textEdit_10.setEnabled(False)
        self.textEdit_10.setObjectName("textEdit_10")
        self.gridLayout_2.addWidget(self.textEdit_10, 0, 0, 1, 1)
        self.brakefailure = QtWidgets.QCheckBox(parent=self.manual)
        self.brakefailure.setGeometry(QtCore.QRect(340, 360, 91, 20))
        self.brakefailure.setObjectName("brakefailure")
        self.enginefailure = QtWidgets.QCheckBox(parent=self.manual)
        self.enginefailure.setGeometry(QtCore.QRect(340, 380, 101, 20))
        self.enginefailure.setObjectName("enginefailure")
        self.signalfailure = QtWidgets.QCheckBox(parent=self.manual)
        self.signalfailure.setGeometry(QtCore.QRect(340, 400, 91, 20))
        self.signalfailure.setObjectName("signalfailure")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(parent=self.manual)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(800, 140, 191, 331))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.amanualki = QtWidgets.QTextEdit(parent=self.gridLayoutWidget_5)
        self.amanualki.setEnabled(False)
        self.amanualki.setObjectName("amanualki")
        self.gridLayout_5.addWidget(self.amanualki, 1, 0, 1, 1)
        self.kp = QtWidgets.QSpinBox(parent=self.gridLayoutWidget_5)
        self.kp.setObjectName("kp")
        self.gridLayout_5.addWidget(self.kp, 2, 1, 1, 1)
        self.ki = QtWidgets.QSpinBox(parent=self.gridLayoutWidget_5)
        self.ki.setObjectName("ki")
        self.gridLayout_5.addWidget(self.ki, 1, 1, 1, 1)
        self.amanualkp = QtWidgets.QTextEdit(parent=self.gridLayoutWidget_5)
        self.amanualkp.setEnabled(False)
        self.amanualkp.setObjectName("amanualkp")
        self.gridLayout_5.addWidget(self.amanualkp, 2, 0, 1, 1)
        self.apowertext = QtWidgets.QTextEdit(parent=self.gridLayoutWidget_5)
        self.apowertext.setEnabled(False)
        self.apowertext.setObjectName("apowertext")
        self.gridLayout_5.addWidget(self.apowertext, 0, 0, 1, 1)
        self.power = QtWidgets.QLCDNumber(parent=self.gridLayoutWidget_5)
        self.power.setObjectName("power")
        self.gridLayout_5.addWidget(self.power, 0, 1, 1, 1)
        self.textEdit_17 = QtWidgets.QTextEdit(parent=self.manual)
        self.textEdit_17.setEnabled(False)
        self.textEdit_17.setGeometry(QtCore.QRect(320, 10, 171, 61))
        self.textEdit_17.setAutoFillBackground(False)
        self.textEdit_17.setObjectName("textEdit_17")
        self.mode = QtWidgets.QComboBox(parent=self.manual)
        self.mode.setGeometry(QtCore.QRect(320, 70, 171, 51))
        self.mode.setObjectName("mode")
        self.mode.addItem("")
        self.mode.addItem("")
        self.textEdit_9 = QtWidgets.QTextEdit(parent=self.manual)
        self.textEdit_9.setGeometry(QtCore.QRect(530, 160, 151, 41))
        self.textEdit_9.setObjectName("textEdit_9")
        self.manualspeed = QtWidgets.QSlider(parent=self.manual)
        self.manualspeed.setGeometry(QtCore.QRect(530, 220, 160, 16))
        self.manualspeed.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.manualspeed.setObjectName("manualspeed")
        self.textEdit_12 = QtWidgets.QTextEdit(parent=self.manual)
        self.textEdit_12.setEnabled(False)
        self.textEdit_12.setGeometry(QtCore.QRect(510, 10, 201, 71))
        self.textEdit_12.setObjectName("textEdit_12")
        self.servicebrake = QtWidgets.QSlider(parent=self.manual)
        self.servicebrake.setGeometry(QtCore.QRect(530, 90, 160, 16))
        self.servicebrake.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.servicebrake.setObjectName("servicebrake")
        self.gridLayoutWidget_7 = QtWidgets.QWidget(parent=self.manual)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(500, 260, 281, 231))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.textEdit_11 = QtWidgets.QTextEdit(parent=self.gridLayoutWidget_7)
        self.textEdit_11.setEnabled(False)
        self.textEdit_11.setObjectName("textEdit_11")
        self.gridLayout_7.addWidget(self.textEdit_11, 1, 0, 1, 1)
        self.amanualspeedtext = QtWidgets.QTextEdit(parent=self.gridLayoutWidget_7)
        self.amanualspeedtext.setEnabled(False)
        self.amanualspeedtext.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.amanualspeedtext.setObjectName("amanualspeedtext")
        self.gridLayout_7.addWidget(self.amanualspeedtext, 2, 0, 1, 1)
        self.currentspeed = QtWidgets.QLCDNumber(parent=self.gridLayoutWidget_7)
        self.currentspeed.setObjectName("currentspeed")
        self.gridLayout_7.addWidget(self.currentspeed, 1, 1, 1, 1)
        self.commandedspeed = QtWidgets.QLCDNumber(parent=self.gridLayoutWidget_7)
        self.commandedspeed.setObjectName("commandedspeed")
        self.gridLayout_7.addWidget(self.commandedspeed, 2, 1, 1, 1)
        self.tabWidget.addTab(self.manual, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.textEdit_47 = QtWidgets.QTextEdit(parent=self.tab)
        self.textEdit_47.setGeometry(QtCore.QRect(450, 380, 111, 31))
        self.textEdit_47.setObjectName("textEdit_47")
        self.textEdit_48 = QtWidgets.QTextEdit(parent=self.tab)
        self.textEdit_48.setGeometry(QtCore.QRect(633, 380, 111, 31))
        self.textEdit_48.setObjectName("textEdit_48")
        self.tbexteriorlights = QtWidgets.QCheckBox(parent=self.tab)
        self.tbexteriorlights.setGeometry(QtCore.QRect(450, 410, 121, 31))
        self.tbexteriorlights.setObjectName("tbexteriorlights")
        self.tbinteriorlights = QtWidgets.QCheckBox(parent=self.tab)
        self.tbinteriorlights.setGeometry(QtCore.QRect(450, 440, 121, 20))
        self.tbinteriorlights.setObjectName("tbinteriorlights")
        self.tbleftdoor = QtWidgets.QCheckBox(parent=self.tab)
        self.tbleftdoor.setGeometry(QtCore.QRect(640, 420, 101, 20))
        self.tbleftdoor.setObjectName("tbleftdoor")
        self.tbrightdoor = QtWidgets.QCheckBox(parent=self.tab)
        self.tbrightdoor.setGeometry(QtCore.QRect(640, 440, 111, 20))
        self.tbrightdoor.setObjectName("tbrightdoor")
        self.textEdit_65 = QtWidgets.QTextEdit(parent=self.tab)
        self.textEdit_65.setGeometry(QtCore.QRect(420, 30, 161, 51))
        self.textEdit_65.setObjectName("textEdit_65")
        self.tbannouncement = QtWidgets.QComboBox(parent=self.tab)
        self.tbannouncement.setGeometry(QtCore.QRect(420, 80, 161, 31))
        self.tbannouncement.setObjectName("tbannouncement")
        self.textEdit_66 = QtWidgets.QTextEdit(parent=self.tab)
        self.textEdit_66.setGeometry(QtCore.QRect(630, 200, 131, 31))
        self.textEdit_66.setObjectName("textEdit_66")
        self.tbbrakefailure = QtWidgets.QCheckBox(parent=self.tab)
        self.tbbrakefailure.setGeometry(QtCore.QRect(640, 240, 101, 20))
        self.tbbrakefailure.setObjectName("tbbrakefailure")
        self.tbenginefailure = QtWidgets.QCheckBox(parent=self.tab)
        self.tbenginefailure.setGeometry(QtCore.QRect(640, 260, 101, 20))
        self.tbenginefailure.setObjectName("tbenginefailure")
        self.tbsignalfailure = QtWidgets.QCheckBox(parent=self.tab)
        self.tbsignalfailure.setGeometry(QtCore.QRect(640, 280, 101, 20))
        self.tbsignalfailure.setObjectName("tbsignalfailure")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 20, 311, 481))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit_44 = QtWidgets.QTextEdit(parent=self.gridLayoutWidget)
        self.textEdit_44.setObjectName("textEdit_44")
        self.gridLayout.addWidget(self.textEdit_44, 0, 0, 1, 1)
        self.textEdit_46 = QtWidgets.QTextEdit(parent=self.gridLayoutWidget)
        self.textEdit_46.setObjectName("textEdit_46")
        self.gridLayout.addWidget(self.textEdit_46, 4, 0, 1, 1)
        self.textEdit_45 = QtWidgets.QTextEdit(parent=self.gridLayoutWidget)
        self.textEdit_45.setObjectName("textEdit_45")
        self.gridLayout.addWidget(self.textEdit_45, 2, 0, 1, 1)
        self.tbauthority = QtWidgets.QTextEdit(parent=self.gridLayoutWidget)
        self.tbauthority.setObjectName("tbauthority")
        self.gridLayout.addWidget(self.tbauthority, 2, 1, 1, 1)
        self.tbcurrentspeed = QtWidgets.QTextEdit(parent=self.gridLayoutWidget)
        self.tbcurrentspeed.setObjectName("tbcurrentspeed")
        self.gridLayout.addWidget(self.tbcurrentspeed, 0, 1, 1, 1)
        self.tbtemp = QtWidgets.QTextEdit(parent=self.gridLayoutWidget)
        self.tbtemp.setObjectName("tbtemp")
        self.gridLayout.addWidget(self.tbtemp, 4, 1, 1, 1)
        self.tbcommandespeed = QtWidgets.QTextEdit(parent=self.gridLayoutWidget)
        self.tbcommandespeed.setObjectName("tbcommandespeed")
        self.gridLayout.addWidget(self.tbcommandespeed, 1, 1, 1, 1)
        self.textEdit_50 = QtWidgets.QTextEdit(parent=self.gridLayoutWidget)
        self.textEdit_50.setObjectName("textEdit_50")
        self.gridLayout.addWidget(self.textEdit_50, 1, 0, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(parent=self.tab)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(430, 180, 150, 150))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.textEdit_58 = QtWidgets.QTextEdit(parent=self.gridLayoutWidget_4)
        self.textEdit_58.setObjectName("textEdit_58")
        self.gridLayout_4.addWidget(self.textEdit_58, 1, 0, 1, 1)
        self.tbkp = QtWidgets.QTextEdit(parent=self.gridLayoutWidget_4)
        self.tbkp.setObjectName("tbkp")
        self.gridLayout_4.addWidget(self.tbkp, 1, 1, 1, 1)
        self.textEdit_57 = QtWidgets.QTextEdit(parent=self.gridLayoutWidget_4)
        self.textEdit_57.setObjectName("textEdit_57")
        self.gridLayout_4.addWidget(self.textEdit_57, 0, 0, 1, 1)
        self.tbki = QtWidgets.QTextEdit(parent=self.gridLayoutWidget_4)
        self.tbki.setObjectName("tbki")
        self.gridLayout_4.addWidget(self.tbki, 0, 1, 1, 1)
        self.tbapply = QtWidgets.QPushButton(parent=self.tab)
        self.tbapply.setGeometry(QtCore.QRect(620, 10, 151, 101))
        self.tbapply.setObjectName("tbapply")
        self.tabWidget.addTab(self.tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1059, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.brakefailure.setDisabled(True)
        self.enginefailure.setDisabled(True)
        self.signalfailure.setDisabled(True)
        self.time.setDisabled(True)
        self.authority.setDisabled(True)
        self.nextstop.setDisabled(True)
        self.currentspeed.setDisabled(True)
        self.power.setDisabled(True)
        self.speedlimit.setDisabled(True)
        self.textEdit_9.setDisabled(True)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.leftdoor.setText(_translate("MainWindow", "Left Door Open"))
        self.rightdoor.setText(_translate("MainWindow", "Right Door Open"))
        self.internallight.setText(_translate("MainWindow", "Internal Lights On"))
        self.externallight.setText(_translate("MainWindow", "External Lights On"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:700;\">Light Statuses</span></p></body></html>"))
        self.textEdit_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:700;\">Door Statuses</span></p></body></html>"))
        self.ebrake.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.ebrake.setText(_translate("MainWindow", "Emergency Brake"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:700;\">Announcement:</span></p></body></html>"))
        self.announcement.setItemText(0, _translate("MainWindow", "Announcement 1"))
        self.announcement.setItemText(1, _translate("MainWindow", "Announcement 2"))
        self.manualtrainfailures.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:700;\">Train Failures</span></p></body></html>"))
        self.textEdit_8.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:700;\">Temperature</span></p></body></html>"))
        self.authority.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_15.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:700;\">Authority</span></p></body></html>"))
        self.nextstop.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:700;\">Speed Limit</span></p></body></html>"))
        self.amanualnextstop.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:700;\">Next stop:</span></p></body></html>"))
        self.textEdit_10.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:700;\">Time:</span></p></body></html>"))
        self.brakefailure.setText(_translate("MainWindow", "Brake Failure"))
        self.enginefailure.setText(_translate("MainWindow", "Engine Failure"))
        self.signalfailure.setText(_translate("MainWindow", "Signal Failure"))
        self.amanualki.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Integral Gain (Ki):</span></p></body></html>"))
        self.amanualkp.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Proportional Gain (Kp):</span></p></body></html>"))
        self.apowertext.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:700; font-style:italic; text-decoration: underline;\">Power (W)</span></p></body></html>"))
        self.textEdit_17.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:700; font-style:italic; text-decoration: underline;\">Mode:</span></p></body></html>"))
        self.mode.setItemText(0, _translate("MainWindow", "Automatic"))
        self.mode.setItemText(1, _translate("MainWindow", "Manual"))
        self.textEdit_9.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:700;\">Manual Velocity</span></p></body></html>"))
        self.textEdit_12.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:700;\">Service Brake</span></p></body></html>"))
        self.textEdit_11.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:700; font-style:italic; text-decoration: underline;\">Current Speed (miles/hr)</span></p></body></html>"))
        self.amanualspeedtext.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:700; font-style:italic; text-decoration: underline;\">Commanded Speed (miles/hr)</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.manual), _translate("MainWindow", "Main Page"))
        self.textEdit_47.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Lights</p></body></html>"))
        self.textEdit_48.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Doors</p></body></html>"))
        self.tbexteriorlights.setText(_translate("MainWindow", "Exterior Lights On"))
        self.tbinteriorlights.setText(_translate("MainWindow", "Interior Lights On"))
        self.tbleftdoor.setText(_translate("MainWindow", "Left Door Open"))
        self.tbrightdoor.setText(_translate("MainWindow", "Right Door Open"))
        self.textEdit_65.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Input Announcement</p></body></html>"))
        self.textEdit_66.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Train Failures</span></p></body></html>"))
        self.tbbrakefailure.setText(_translate("MainWindow", "Brake Failure"))
        self.tbenginefailure.setText(_translate("MainWindow", "Engine Failure"))
        self.tbsignalfailure.setText(_translate("MainWindow", "Signal Failure"))
        self.textEdit_44.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Current Speed (miles/hr)</p></body></html>"))
        self.textEdit_46.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Temperature (Fahrenheit)</p></body></html>"))
        self.textEdit_45.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Authority (miles)</p></body></html>"))
        self.textEdit_50.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Commanded speed (miles/hr)</p></body></html>"))
        self.textEdit_58.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Kp</p></body></html>"))
        self.textEdit_57.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Ki</p></body></html>"))
        self.tbapply.setText(_translate("MainWindow", "Apply"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Test Bench"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
